import mongoose from "mongoose";

/**
 * AiChatSession Schema — stores persistent conversation threads
 */
const aiChatSessionSchema = new mongoose.Schema(
  {
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      default: null,
      index: true,
    },
    visitorId: {
      type: String,
      default: null,
      index: true,
    },
    title: {
      type: String,
      default: "New Fashion Conversation",
      trim: true,
    },
    summary: {
      type: String,
      default: "",
    },
    isPinned: {
      type: Boolean,
      default: false,
    },
    tags: {
      type: [String],
      default: [],
    },
    lastMessageAt: {
      type: Date,
      default: Date.now,
      index: true,
    },
  },
  { timestamps: true }
);

/**
 * Sub-schema for items inside an AI Outfit or Tech Setup bundle
 */
const bundleItemSchema = new mongoose.Schema(
  {
    tier: {
      type: String, // e.g. 'Headwear', 'Topwear', 'Bottomwear', 'Footwear', 'Peripheral', 'Component'
      required: true,
    },
    product: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Product",
      required: true,
    },
    variantId: {
      type: mongoose.Schema.Types.ObjectId,
      default: null,
    },
    title: {
      type: String,
      required: true,
    },
    price: {
      type: Number,
      required: true,
    },
    originalPrice: {
      type: Number,
      default: null,
    },
    image: {
      type: String,
      default: "",
    },
    selectedAttributes: {
      type: Map,
      of: String,
      default: {},
    },
    stockStatus: {
      type: String,
      default: "instock",
    },
  },
  { _id: false }
);

/**
 * Sub-schema for complete multi-tier outfit or tech setups
 */
const bundleSchema = new mongoose.Schema(
  {
    bundleId: {
      type: String,
      required: true,
    },
    type: {
      type: String,
      enum: ["outfit", "setup", "custom"],
      default: "outfit",
    },
    title: {
      type: String,
      required: true,
    },
    description: {
      type: String,
      default: "",
    },
    totalPrice: {
      type: Number,
      required: true,
    },
    savings: {
      type: Number,
      default: 0,
    },
    items: [bundleItemSchema],
  },
  { _id: false }
);

/**
 * AiChatMessage Schema — stores each user/assistant turn including tool metadata & bundles
 */
const aiChatMessageSchema = new mongoose.Schema(
  {
    session: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "AiChatSession",
      required: true,
      index: true,
    },
    role: {
      type: String,
      enum: ["user", "assistant", "system", "tool"],
      required: true,
    },
    content: {
      type: String,
      default: "",
    },
    // Uploaded or captured image references
    images: [
      {
        url: { type: String, required: true },
        name: { type: String, default: "" },
        mimeType: { type: String, default: "image/jpeg" },
        embedding: { type: [Number], select: false, default: [] },
      },
    ],
    // Structured tool calls & results
    toolCalls: [
      {
        toolName: { type: String, required: true },
        args: { type: mongoose.Schema.Types.Mixed },
        result: { type: mongoose.Schema.Types.Mixed },
        status: { type: String, enum: ["pending", "success", "failed"], default: "success" },
      },
    ],
    // Multi-tier outfits or product setups generated by the agent
    bundles: [bundleSchema],
    // Individual products referenced in this response
    products: [
      {
        type: mongoose.Schema.Types.ObjectId,
        ref: "Product",
      },
    ],
    // Perplexity-style citations / sources
    sources: [
      {
        title: { type: String, default: "" },
        url: { type: String, default: "" },
        type: { type: String, default: "catalog" }, // 'catalog' | 'review' | 'guide'
        productId: { type: mongoose.Schema.Types.ObjectId, ref: "Product", default: null },
      },
    ],
    // Metadata about which model served this query
    modelUsed: {
      type: String,
      default: "gemini-2.0-flash",
    },
    isError: {
      type: Boolean,
      default: false,
    },
  },
  { timestamps: true }
);

export const AiChatSession = mongoose.model("AiChatSession", aiChatSessionSchema);
export const AiChatMessage = mongoose.model("AiChatMessage", aiChatMessageSchema);
